[project]
name = "parkings-weather-correlation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas>=2.2.3",
    "prophet>=1.1.6",
]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
]
